FROM postgres:16-alpine

COPY scripts/postgres-init-readonly.sh /docker-entrypoint-initdb.d/20-readonly.sh
RUN sed -i 's/\r$//' /docker-entrypoint-initdb.d/20-readonly.sh \
    && chmod 755 /docker-entrypoint-initdb.d/20-readonly.sh
